### ISSUE TITLE
About Open Source Virtual Background

### ISSUE THREAD

**Issue by tomchor** [BenTheElder/site#9]
Sorry to contact you through this issue! But short of sending you an email, I don't really know how else to contact you since I don't have twitter!

I thought this [virtual background you implemented](https://elder.dev/posts/open-source-virtual-background/) was super cool! I unfortunately couldn't understand all of your steps so I was wondering if you'd considering sharing the code/steps on a github repo? I think it would actually help a lot of people that have Linux but also wanna have decent virtual background in Zoom meetings. So far I haven't been able to get anything to work and it seems like your solution is pretty cool.

Thanks!

**Comment by BenTheElder** [comment]
Hi, thanks for the kind words and your interest.

All of the code is throughout the post, I don't really have the time to maintain a project like this (I already maintain much larger open source projects pretty much all day everyday), and there's a releasing process I'd have to go through at my current employer so I've let others do as they wish with the snippets from the post. There are a number of projects based on this if you search GitHub for the post URL or similar. I don't have any particular one to endorse but hopefully one of them is helpful!

Also FWIW the implementation in that post mostly covers how you might hack together something like this, it has low hanging performance fails. I no longer need this much (most of my video calls are in Meet which now supports this very well from the web client everywhere) and haven't found time to hack on it much further. Hopefully one of the derived projects serves you better 😅

**Comment by tomchor** [comment]
I appreciate the feedback! I'll try to look up one of the derived projects.

Cheers!
